### DISCUSSION TITLE
How to deploy the cookbook?

### DISCUSSION THREAD

**Discussion by rodriguesfred** [best-practice-and-impact/afcharts-py#22] [Q&A] [answered]
How do I deploy the cookbook? Its working locally but I don't know how to deploy it.

I created a workflow called deploy.yml but its not even showing in the actions. Help!

**Comment by rodriguesfred** [comment]
@nickhenden
@TomFarley you've sucessfully created actions any ideas?

**Reply by nickhenden** [reply, marked as answer]
For testing you'll need to include the name of your branch in the list of branches that trigger the workflow when they're pushed to, i.e.
```
on:
  workflow_dispatch:
  push:
    branches: [main, dev, fr/testing-cookbook-deploy-action]
```
